"""
query.py — Milestone 5: Grounded Generation
LLM:      Groq llama-3.3-70b-versatile (free tier)
Grounding: model instructed to answer ONLY from retrieved context.
Sources:  appended programmatically from metadata — NOT generated by the LLM.
"""

import os
from groq import Groq
from dotenv import load_dotenv
import chromadb
from sentence_transformers import SentenceTransformer

load_dotenv()  # reads GROQ_API_KEY from .env

# ── CONFIG ───────────────────────────────────────────────────────────────────
CHROMA_PATH = "./chroma_db"
COLLECTION  = "tech_career_advice"
EMBED_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL   = "llama-3.3-70b-versatile"
TOP_K       = 5

# ── LAZY-LOAD SINGLETONS (load once, reuse across calls) ────────────────────
_embed_model = None
_collection  = None
_groq_client = None

def _load():
    global _embed_model, _collection, _groq_client
    if _embed_model is None:
        _embed_model = SentenceTransformer(EMBED_MODEL)
    if _collection is None:
        db = chromadb.PersistentClient(path=CHROMA_PATH)
        _collection = db.get_collection(COLLECTION)
    if _groq_client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise ValueError(
                "GROQ_API_KEY not found. Add it to your .env file:\n"
                "  GROQ_API_KEY=your_key_here\n"
                "Get a free key at https://console.groq.com"
            )
        _groq_client = Groq(api_key=api_key)


# ── 1. RETRIEVE ──────────────────────────────────────────────────────────────

def retrieve(question, k=TOP_K):
    """Embed the question and return the top-k chunks with metadata."""
    _load()
    embedding = _embed_model.encode([question]).tolist()
    results   = _collection.query(
        query_embeddings = embedding,
        n_results        = k,
        include          = ["documents", "metadatas", "distances"],
    )
    return [
        {
            "text":     text,
            "source":   meta["source"],
            "distance": dist,
        }
        for text, meta, dist in zip(
            results["documents"][0],
            results["metadatas"][0],
            results["distances"][0],
        )
    ]


# ── 2. GENERATE (strictly grounded) ─────────────────────────────────────────

# This system prompt enforces grounding — it does not merely suggest it.
# "Do NOT use your general training knowledge" is the critical line.
SYSTEM_PROMPT = """You are a tech career advisor that answers questions strictly from provided documents.

Rules you must follow without exception:
1. Answer ONLY using information explicitly present in the context documents below.
2. If the context does not contain enough information to answer the question, respond with exactly: "I don't have enough information in my documents to answer that."
3. Do NOT draw on your general training knowledge. Do NOT fill gaps with plausible-sounding information.
4. Be specific and cite details from the text — vague general advice is a grounding failure.
5. Do NOT mention sources in your answer — they are added separately."""


def generate(question, chunks):
    """Send retrieved chunks + question to the LLM. Returns grounded answer text."""
    _load()

    # Build context block — each chunk labelled with its source file
    context = "\n\n---\n\n".join(
        f"[Source: {c['source']}]\n{c['text']}" for c in chunks
    )

    user_message = f"""Context documents:
{context}

Question: {question}

Answer using ONLY the context above. Do not use outside knowledge:"""

    response = _groq_client.chat.completions.create(
        model    = LLM_MODEL,
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
        temperature = 0.2,   # low = more factual, less creative
        max_tokens  = 512,
    )
    return response.choices[0].message.content.strip()


# ── 3. ASK — end-to-end pipeline ─────────────────────────────────────────────

def ask(question):
    """
    Full RAG pipeline: retrieve → generate → return answer + sources.

    Returns a dict:
        answer  (str)        — LLM response grounded in retrieved context
        sources (list[str])  — unique source filenames, added programmatically
        chunks  (list[dict]) — raw retrieved chunks (useful for debugging)
    """
    chunks  = retrieve(question)
    answer  = generate(question, chunks)

    # Sources are extracted from metadata — the LLM never decides what to cite.
    sources = list(dict.fromkeys(c["source"] for c in chunks))

    return {"answer": answer, "sources": sources, "chunks": chunks}


# ── 4. CLI TEST ──────────────────────────────────────────────────────────────

TEST_QUERIES = [
    "What should I put on my resume if I have no experience?",
    "How do I negotiate a higher salary offer?",
    "How many LeetCode problems do I need to solve before interviews?",
    "Is a coding bootcamp worth it for getting a tech job?",
    "How do I get a referral at a big tech company?",
]

if __name__ == "__main__":
    print("Testing end-to-end grounded generation...\n")
    for q in TEST_QUERIES:
        print("=" * 60)
        print(f"Q: {q}")
        print("=" * 60)
        result = ask(q)
        print(f"\nA: {result['answer']}")
        print(f"\nSources: {', '.join(result['sources'])}")
        print()
